# Generated by Django 5.1.4 on 2025-01-07 01:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calorie_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='food_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_food_log', to='calorie_app.foodlog'),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='date_consumed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
